In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
from torch import nn
from sklearn.model_selection import KFold

https://github.com/christianversloot/machine-learning-articles/blob/main/how-to-use-k-fold-cross-validation-with-pytorch.md

In [10]:
RAMAN_DATASET_PATH = "./data/raman_diabetis_spectroscopy/"
XENON_DATASET_PATH = "./data/xenon/"

In [86]:
dset_name = 'vein'
d = pd.read_csv(RAMAN_DATASET_PATH+dset_name+'.csv')
d = d.iloc[1:,:]
y = d.iloc[:,1].astype(int)
X = d.iloc[:,800:1800]
means = X.mean(0).to_frame().T
means = means._append([means]*20, ignore_index=True).iloc[1:]
X = X - means

In [90]:
X_neg, y_neg = X[y==0], y[y==0]
X_pos, y_pos = X[y==1], y[y==1]


In [30]:
class MLP(nn.Module):
    def __init__(self):
        super.__init__()
        self.layers = nn.Sequential(
            nn.Linear(1000, 14),
            nn.ReLU(),
            nn.Linear(14, 2)
        )
    
    def forward(self, x):
        return self.layers(x)

In [96]:
n = 5
kf1 = KFold(n_splits=n)
kf2 = KFold(n_splits=n)
for train, test in kf1.split(X_pos):
    for train1, test1 in kf2.split(X_neg):
        print("%s %s %s %s" % (train, test, train1, test1))

[ 3  4  5  6  7  8  9 10] [0 1 2] [2 3 4 5 6 7 8] [0 1]
[ 3  4  5  6  7  8  9 10] [0 1 2] [0 1 4 5 6 7 8] [2 3]
[ 3  4  5  6  7  8  9 10] [0 1 2] [0 1 2 3 6 7 8] [4 5]
[ 3  4  5  6  7  8  9 10] [0 1 2] [0 1 2 3 4 5 8] [6 7]
[ 3  4  5  6  7  8  9 10] [0 1 2] [0 1 2 3 4 5 6 7] [8]
[ 0  1  2  5  6  7  8  9 10] [3 4] [2 3 4 5 6 7 8] [0 1]
[ 0  1  2  5  6  7  8  9 10] [3 4] [0 1 4 5 6 7 8] [2 3]
[ 0  1  2  5  6  7  8  9 10] [3 4] [0 1 2 3 6 7 8] [4 5]
[ 0  1  2  5  6  7  8  9 10] [3 4] [0 1 2 3 4 5 8] [6 7]
[ 0  1  2  5  6  7  8  9 10] [3 4] [0 1 2 3 4 5 6 7] [8]
[ 0  1  2  3  4  7  8  9 10] [5 6] [2 3 4 5 6 7 8] [0 1]
[ 0  1  2  3  4  7  8  9 10] [5 6] [0 1 4 5 6 7 8] [2 3]
[ 0  1  2  3  4  7  8  9 10] [5 6] [0 1 2 3 6 7 8] [4 5]
[ 0  1  2  3  4  7  8  9 10] [5 6] [0 1 2 3 4 5 8] [6 7]
[ 0  1  2  3  4  7  8  9 10] [5 6] [0 1 2 3 4 5 6 7] [8]
[ 0  1  2  3  4  5  6  9 10] [7 8] [2 3 4 5 6 7 8] [0 1]
[ 0  1  2  3  4  5  6  9 10] [7 8] [0 1 4 5 6 7 8] [2 3]
[ 0  1  2  3  4  5  6  9 10] [7 8] [